-- Canonical pre-migration baseline for public objects that existed before
-- supabase_migrations.schema_migrations begins at version 20260814 in LIVE.
-- This is a baseline snapshot, NOT a fabricated historical migration.
-- It contains schema only and no production rows.

begin;

create table public.products (
  id text primary key,
  ref text,
  produto text not null,
  categoria text not null,
  preco numeric not null,
  imagens jsonb not null default '[]'::jsonb,
  link text not null,
  ativo boolean default true,
  destaque boolean default false,
  status text default 'published'::text,
  created_by text default 'system'::text,
  slug text,
  descricao text,
  pagina_ponte_url text,
  created_at timestamptz default now()
);

alter table public.products enable row level security;
revoke all on table public.products from public, anon, authenticated;

create table public.catalog_categories (
  name text primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.catalog_categories enable row level security;
revoke all on table public.catalog_categories from public, anon, authenticated;

create table public.product_clicks (
  id bigint generated by default as identity primary key,
  product_id text not null,
  product_slug text,
  product_name text,
  product_price numeric default 0.00,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  fbclid text,
  gclid text,
  ttclid text,
  referrer text,
  landing_page text,
  user_agent text,
  ip_address text,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index idx_product_clicks_created_at on public.product_clicks (created_at);
create index idx_product_clicks_product_id on public.product_clicks (product_id);
create index idx_product_clicks_product_slug on public.product_clicks (product_slug);

alter table public.product_clicks enable row level security;
revoke all on table public.product_clicks from public, anon, authenticated;

commit;
